### ISSUE TITLE
The error message in syntax checker

### ISSUE THREAD

**Issue by DinaGala** [plinscho/minishell#44]
Sometimes a part of the message is missing:

minishell$> >>"">>"">>""
minishell: syntax error near unexpected token 

minishell$> >>>
minishell: syntax error near unexpected token 'newline'

minishell$> |
minishell: syntax error near unexpected token |

minishell$> <<<
minishell: syntax error near unexpected token

**Comment by plinscho** [comment]
Fixed all cases
